# Generated by Django 4.2.19 on 2025-02-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymclasses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymClasses',
        ),
    ]
