# Generated by Django 4.2.19 on 2025-02-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymclasses', '0003_rename_description_gymclasses_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymclasses',
            old_name='excert',
            new_name='excerpt',
        ),
    ]
